spring:
  application:
    name: sentinel-ticketing

  # 1. ENABLING VIRTUAL THREADS (The "Java 21" way)
  threads:
    virtual:
      enabled: true

  # 2. DATABASE CONFIG
  datasource:
    url: jdbc:postgresql://localhost:5432/sentinel_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # 3. REDIS CONFIG
  data:
    redis:
      host: localhost
      port: 6379

  # 4. KAFKA CONFIG
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer